//actions for more than 1 role
export const SIGN_UP = 'SIGN_UP';

//actions for user
export const USERSIGN_IN = 'USERSIGN_IN';
export const ADD_ARTICLE = 'DEL_ARTICLE';
export const DEL_ARTICLE = 'DEL_ARTICLE';
export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ARTICLE_TOTAL = 'GET_ARTICLE_TOTAL'
export const GET_USEREVENT = 'GET_USEREVENT';
export const GET_USERJOINEDEVENT = 'GET_USERJOINEDEVENT';
export const USER_JOINEVENT = 'USER_JOINEVENT';
export const GET_USERPROFILE = 'GET_USEPROFILE';
export const EDIT_USERPROFILE = 'EDIT_USERPROFILE';
export const SEARCH_ARTICLE = 'SEARCH_ARTICLE';
export const SEARCH_EVENT = 'SEARCH_EVENT';
export const EDIT_USERPHOTO = 'EDIT_USERPRHOTO';
export const GET_USERSKILLSET = 'GET_USERSKILLSET'
export const USER_FORGOTPASSWORD = 'USER_FORGOTPASSWORD'

//actions for organization
export const ADD_EVENT = 'ADD_EVENT';
export const GET_EVENT = 'GET_EVENT';
export const DEL_EVENT = 'DEL_EVENT';
export const EDIT_EVENT = 'EDIT_EVENT';
export const EDIT_EVENT_PHOTO = 'EDIT_EVENT_PHOTO';
export const GET_SKILLSET = 'GET_SKILLSET';
export const GET_PROFILE = 'GET_PROFILE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_PHOTO = 'EDIT_PROFILE_PHOTO';
export const GET_VOLUNTEER = 'GET_VOLUNTEER';
export const SEARCH_VOLUNTEER = 'SEARCH_VOLUNTEER';
export const SIGN_IN_ORG = 'SIGN_IN_ORG';
export const GET_APPLICANT = 'GET_APPLICANT';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const ACCEPT_VOLUNTEER = 'ACCEPT_VOLUNTEER';
export const REJECT_VOLUNTEER = 'REJECT_VOLUNTEER';
export const DEL_ORGANIZATION = 'DEL_ORGANIZATION'
export const DEL_SKILLSET = 'DEL_SKILLSET'
export const GET_ORGANIZATION = 'GET_ORGANIZATION'

//actions for admin
export const GET_USER = 'GET_USER';
export const DEL_USER = 'DEL_USER'
export const ADD_USER = 'ADD_USER'
export const GET_USER_TOTAL = 'GET_USER_TOTAL'
export const GET_EVENT_TOTAL = 'GET_EVENT_TOTAL'
export const GET_ORGANIZATION_TOTAL = 'GET_ORGANIZATION_TOTAL'
export const SIGNIN_ADMIN = 'SIGNIN_ADMIN'
export const GET_PROFILE_ADMIN = 'GET_PROFILE_ADMIN'
export const EDIT_PROFILE_ADMIN = 'EDIT_PROFILE_ADMIN'



